import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FNAV from "./components/firstnav/page";
import SNAV from "./components/snav/page";
import Footer from "./components/footer/page";
import { Providers } from "./providers";
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Fll stack Nike E-Commerce",
  description: "Generated by Syed Mujtaba Abbas",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <FNAV />
          <SNAV />
          {children}
          <Footer />
          <Toaster
            position="top-center"
            expand={true}
            richColors
            closeButton
            theme="light"
            toastOptions={{
              style: {
                background: 'white',
                color: 'black',
                border: '1px solid #E2E8F0',
                borderRadius: '8px',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
              },
            }}
          />
        </Providers>
      </body>
    </html>
  )
}
